version: "2"

services:
    prestashop:
        image: docker-prestashop
        ports:
            - 80:80
            - 443:443
        depends_on:
            - mysql
        environment:
            - PS_DEV_MODE=1
            - DB_SERVER=mysql
            - DB_USER=root
            - DB_PASSWD=root
            - DB_NAME=prestashop

    mysql:
        image: mariadb
        volumes:
            - ./docker/mariadb:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=prestashop

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        ports:
            - 81:80
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
