version: "2"

services:
    prestashop:
        image: docker-prestashop
        ports:
            - 18128:80
            - 18129:443
        depends_on:
            - mysql
        environment:
            - PS_DEV_MODE=1
            - DB_SERVER=mysql
            - DB_USER=root
            - DB_PASSWD=root
            - DB_NAME=prestashop

networks:
    default:
        name: prestashop-net
