version: "2"

services:
    teamB:
        image: torvey/be_181291
        ports:
            - 18128:80
            - 18129:443
        environment:
            - PS_DEV_MODE=1
            - DB_SERVER=actina15.maas
            - DB_USER=be_181291
            - DB_PASSWD=politechnika123
            - DB_NAME=be_181291
        restart: always
