<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPy87hqr\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPy87hqr/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPy87hqr.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPy87hqr\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPy87hqr\appProdProjectContainer([
    'container.build_hash' => 'Py87hqr',
    'container.build_id' => '75e5ad4f',
    'container.build_time' => 1637965675,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPy87hqr');
