<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOwnyn9w\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOwnyn9w/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOwnyn9w.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOwnyn9w\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOwnyn9w\appProdProjectContainer([
    'container.build_hash' => 'Ownyn9w',
    'container.build_id' => '49f6e547',
    'container.build_time' => 1637256743,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOwnyn9w');
