<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJhufk1j\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJhufk1j/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJhufk1j.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJhufk1j\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJhufk1j\appProdProjectContainer([
    'container.build_hash' => 'Jhufk1j',
    'container.build_id' => '49a375aa',
    'container.build_time' => 1637499787,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJhufk1j');
